# Generated by Django 5.1.1 on 2024-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=250)),
                ('extrafield', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('save_info', models.BooleanField(default=False)),
            ],
        ),
    ]
